app:
  version: "project_version"
  auth:
    tg-bot-token: ${TG_BOT_TOKEN}
    tg-bot-username: "jw_helpers_bot"
    username-white-list: ANY # use tg ids for it
  chat-id: -1001864515510
  message-template: | 
    Є потреба на стенд {0} | {1}
    {2}
    1. {3}
    2. {4}
    3. {5}
    4. {6}

server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: SUS_JW
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:postgresql://localhost:5432/sus_jw_db
    username: sus_jw_user
    password: 9m4tRc91i1TvMa4H
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    defaultSchema: public
    validateOnMigrate: false
    baselineOnMigrate: true
    url: jdbc:postgresql://postgres:5432/sus_jw_db
    user: sus_jw_user
    password: 9m4tRc91i1TvMa4H
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
