version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sus_jw_server
    container_name: sus_jw_server
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sus_jw_db
      SPRING_DATASOURCE_USERNAME: sus_jw_user
      SPRING_DATASOURCE_PASSWORD: 9m4tRc91i1TvMa4H
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: sus_jw_db
    restart: always
    environment:
      POSTGRES_USER: sus_jw_user
      POSTGRES_PASSWORD: 9m4tRc91i1TvMa4H
      POSTGRES_DB: sus_jw_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
