-- Drop all
drop table if exists stand_day_attendees cascade;
drop table if exists stand_day_time_frames cascade;
drop table if exists stand_days cascade;
drop table if exists stands cascade;
drop table if exists time_frames cascade;
drop table if exists users cascade;

-- Users
create table users (
    primary key (id),
    id bigint generated by default as identity,
    telegram_id bigint,
    meeting_id bigint,
    username varchar(255) not null unique,
    first_name varchar(255) not null,
    last_name varchar(255),
    photo_url varchar(255)
);

-- Time frames
create table time_frames (
    primary key (id),
    id bigint generated by default as identity,
    from_time time(0) not null,
    to_time time(0) not null,
    constraint unique_from_to unique (from_time, to_time),
    constraint check_no_seconds_from_time check (extract(second from from_time) = 0),
    constraint check_no_seconds_to_time check (extract(second from to_time) = 0)
);

-- Stands
create table stands (
    primary key (id),
    id bigint generated by default as identity,
    name varchar(255) not null,
    description varchar(255),
    latitude float(53),
    longitude float(53)
);

-- Stands days
create table stand_days (
    primary key (id),
    id bigint generated by default as identity,
    date date not null,
    stand_id bigint not null
);

alter table if exists stand_days add constraint fk_stand_days_stand_id
    foreign key (stand_id) references stands;

-- Stand day time frames
create table stand_day_time_frames (
    stand_day_id bigint not null,
    time_frame_id bigint not null,
    constraint unique_stand_day_time_frame unique (stand_day_id, time_frame_id)
);

alter table if exists stand_day_time_frames add constraint fk_stand_day_time_frames_time_frame_id
    foreign key (time_frame_id) references time_frames;

alter table if exists stand_day_time_frames add constraint fk_stand_day_time_frames_stand_day_time_frames
    foreign key (stand_day_id) references stand_days;

-- Stand day attendees
create table stand_day_attendees (
    user_id bigint not null,
    stand_day_time_frame_id bigint not null
);

alter table if exists stand_day_attendees add constraint fk_stand_day_attendees_user_id
    foreign key (user_id) references users;

alter table if exists stand_day_attendees add constraint fk_stand_day_attendees_stand_day_time_frame_id
    foreign key (stand_day_time_frame_id) references stand_days;