create table groups (
    primary key (id),
    id bigint generated by default as identity,
    meeting_id bigint not null,
    name varchar(255),
    description varchar(255)
);

create table groups_users (
    group_id bigint not null,
    user_id bigint not null
);

create table meetings (
    primary key (id),
    id bigint generated by default as identity,
    name varchar(255),
    description varchar(255)
);

-- Add a foreign key constraint for `groups.meeting_id` referencing `meetings.id`
alter table if exists groups
add constraint fk_groups_meetings_meeting_id
foreign key (meeting_id)
references meetings(id);

-- Add a unique constraint for `groups_users.user_id`
alter table if exists groups_users
add constraint uk_groups_users_user_id
unique (user_id);

-- Add a foreign key constraint for `groups_users.user_id` referencing `users.id`
alter table if exists groups_users
add constraint fk_groups_users_user_id
foreign key (user_id)
references users(id);

-- Add a foreign key constraint for `groups_users.group_id` referencing `groups.id`
alter table if exists groups_users
add constraint fk_groups_users_group_id
foreign key (group_id)
references groups(id);